### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by chadsly** [keitaroinc/ckan-helm#100]
The README references several charts as dependencies
![image](https://github.com/keitaroinc/ckan-helm/assets/9471348/7f9d186b-e40a-4092-8760-a222386760e0)

Looking at the chart.yaml file those dependencies are:
dependencies:
  - name: redis 
    version: 16.5.5
    repository: "https://keitaro-charts.storage.googleapis.com"
    condition: redis.enabled
  - name: solr
    version: 4.1.2
    repository: "https://keitaro-charts.storage.googleapis.com"
    condition: solr.enabled
  - name: postgresql
    version: 10.16.2
    repository: "https://keitaro-charts.storage.googleapis.com"
    condition: postgresql.enabled
  - name: datapusher
    version: 1.0.0
    repository: "https://keitaro-charts.storage.googleapis.com"
    condition: datapusher.enabled

My assumption is that the "https://keitaro-charts.storage.googleapis.com" somehow mirrors the referenced dependencies, but as a user there is no way to verify that.  I recommend updating the README to explicitly state the intent for the referenced dependency charts.

**Comment by ruslanguns** [comment]
I was on the verge of raising this issue due to challenges I faced while deploying CKAN. It seems the README might not accurately reflect the current status of the chart. Could someone provide clarity on the correct repositories, chart, and image versions?

**Comment by stojanovskis1** [comment]
Readme updated in this PR #117
