### ISSUE TITLE
Using CKAN version 2.9.9 fails due to missing 'Loader"

### ISSUE THREAD

**Issue by chadsly** [keitaroinc/ckan-helm#101]
![image](https://github.com/keitaroinc/ckan-helm/assets/9471348/4478e930-ef41-4000-9619-ae32c11c31f9)
Using CKAN version 2.9.9 fails every time.  Switching back to 2.9.8 works successfully.

**Comment by stojanovskis1** [comment]
this is solved with this PR https://github.com/keitaroinc/docker-ckan/pull/113
