### ISSUE TITLE
ckan solr installation error using helm chart

### ISSUE THREAD

**Issue by chaman53** [keitaroinc/ckan-helm#104]
% kubectl logs solr-0 
solr 13:42:11.86 
solr 13:42:11.86 Welcome to the Bitnami solr container
solr 13:42:11.86 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-solr
solr 13:42:11.86 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-solr/issues
solr 13:42:11.86 
solr 13:42:11.87 INFO  ==> ** Starting solr setup **
solr 13:42:11.88 INFO  ==> Validating settings in SOLR_* env vars...
solr 13:42:11.88 ERROR ==> Not enough nodes for the replicas and shards indicated

**Comment by stojanovskis1** [comment]
@chaman53 Hi, can you please provide more details on how are you trying to install, i've tried locally and can't reproduce the issue

**Comment by chaman53** [comment]
This issue got resolved
