### ISSUE TITLE
Request for details on Repository's License

### ISSUE THREAD

**Issue by ruslanguns** [keitaroinc/ckan-helm#105]
I've noticed that it's governed under a custom license. I have a few questions that I hope can be clarified:

- Could you provide a detailed explanation of the terms and conditions of this license?
- How does this custom license compare to more common open-source licenses like MIT, GPL, or Apache 2.0?
- How does this license affect potential contributors?

https://github.com/keitaroinc/ckan-helm/blob/14308000c65a041fe6c7199c1a7aff9a1a8045ec/NOTICE#L2

Thank you for your attention to these questions.

**Comment by stojanovskis1** [comment]
@ruslanguns this is the License for this repository, as you can see it is licensed under the Apache 2.0
https://github.com/keitaroinc/ckan-helm/blob/master/LICENSE

**Comment by ruslanguns** [comment]
@stojanovskis1 thanks so much for clarifying my questions.
