### ISSUE TITLE
ckan 2.9 compatibility

### ISSUE THREAD

**Issue by thilko** [keitaroinc/ckan-helm#11]
We would like to use ckan 2.9 and encounter issues with the helm chart. I.e `paster` is now `ckan`. It is planned to use the helm chart for ckan 2.9?

**Comment by mbocevski** [comment]
@thilko yes the helm chart is compatible, however I did check and there were 2 instances where `paster` was used, I now created a PR #12 that will get merged upon review. Feel free to try it out and let us know if you run into any issues.

**Comment by blazhovsky** [comment]
@thilko changes have been tested and merged for CKAN 2.7, 2.8 and 2.9. Feel free to check out the latest version.

Just as an FYI an official version release will be tagged soon.
