### ISSUE TITLE
activityStreamsEmailNotifications check in cronjob.yaml

### ISSUE THREAD

**Issue by matthiasdg** [keitaroinc/ckan-helm#14]
Currently, in the readme, it says that activityStreamsEmailNotifications is a string, and it is also like that in the default `values.yaml`. However, the `{{- if .Values.ckan.activityStreamsEmailNotifications -}}` will also return true if you change its value to "false", so maybe it should be a boolean (or the check should be changed)?

**Comment by mbocevski** [comment]
@matthiasdg the check has been modified to check for "true" in #15. 

Note that email notifications are broken in 2.9 and we are working on a fix.

**Comment by matthiasdg** [comment]
Thanks! I didn't need the email notifications and noticed the job crashing, so wanted to turn them off, that's how I discovered the faulty check :smile:

**Comment by mbocevski** [comment]
Ok then! Closing as done.

**Comment by mbocevski** [comment]
@matthiasdg in case you will need email notifications, they are now fixed for 2.9 with this PR #16
