### ISSUE TITLE
harvester extension

### ISSUE THREAD

**Issue by danseo-reisys** [keitaroinc/ckan-helm#21]
thanks for sharing this helm chart.
how can one add harvester extension using your helm chart?

**Comment by blazhovsky** [comment]
Hey @danseo-reisys!

Check how we add harvester to our base Docker image [here](https://github.com/keitaroinc/docker-ckan/tree/master/examples/harvest).

After this add harvester in the ckan plugins field in the [values](https://github.com/keitaroinc/ckan-helm/blob/master/values.yaml#L75) and if you need to add any extension specific variables, declare them in the values like shown [here](https://github.com/keitaroinc/ckan-helm/blob/master/values.yaml#L139)

**Comment by blazhovsky** [comment]
Keep in mind though that you will need to expand the deployment with the gather, fetch, run and cleanlog processes. This is not covered in this helm chart and you will have to customize it to achieve what you need.

**Comment by mbocevski** [comment]
One excellent way of doing it is to create a harvester chart with the necessary objects that has a dependency on this ckan chart.

**Comment by danseo-reisys** [comment]
@blazhovsky thanks for the replies.  i'm new to custom helm charts.  can you elaborate what i need to do before running helm install with modified values.yaml?

**Comment by danseo-reisys** [comment]
which ckan version comes with this chart?

**Comment by mbocevski** [comment]
You can configure the image to use in the values https://github.com/keitaroinc/ckan-helm/blob/master/values.yaml#L8-L10, the defaults are using our image for CKAN 2.9.2.

**Comment by danseo-reisys** [comment]
does the package come with paster cli?  how can it be enabled?  Thanks.

**Comment by mbocevski** [comment]
Yes it comes with `paster` for CKAN images for 2.7 and 2.8 and with the `ckan` CLI for CKAN images for 2.9. In order to use the CLIs you need to dock to the CKAN container running on your kubernetes cluster like this for example: `kubectl exec -ti pod_name /bin/bash`

**Comment by danseo-reisys** [comment]
i need to set this variable on the installed ckan instance.  ckan.cors.origin_allow_all = True
where can i find the ini file?

**Comment by danseo-reisys** [comment]
> Yes it comes with `paster` for CKAN images for 2.7 and 2.8 and with the `ckan` CLI for CKAN images for 2.9. In order to use the CLIs you need to dock to the CKAN container running on your kubernetes cluster like this for example: `kubectl exec -ti pod_name /bin/bash`

**Comment by danseo-reisys** [comment]
how can i enable following on already installed ckan instance.   updating production.ini and restart does not keep the change on new pod created. 

ckan.cors.origin_allow_all = true

**Comment by mbocevski** [comment]
Our docker images have installed and enabled the [ckanext-envvars extension](https://github.com/okfn/ckanext-envvars) which allows to configure CKAN through environment variables, check the README of that extension on how to use.

In the helm chart values file we have a space for adding [additional environment configurations ](https://github.com/keitaroinc/ckan-helm/blob/master/values.yaml#L139-L145) to CKAN. So basically for your use case you would add an environment variable there:
`CKAN__CORS__ORIGIN_ALLOW_ALL=true`
