### ISSUE TITLE
How to customize/change the ckan theme

### ISSUE THREAD

**Issue by pribadihcr** [keitaroinc/ckan-helm#23]
Hi, How to we customize / change the ckan's theme?. thanks

**Comment by mbocevski** [comment]
Create your own CKAN extension with your theme following the [CKAN theming guide](https://docs.ckan.org/en/2.9/theming/index.html) from the official CKAN documentation. Once you have your own theme extension you can [extend and build your own docker image](https://github.com/keitaroinc/docker-ckan#extending-ckan-docker-images). Then specify your docker image as part of your deployment in [values](https://github.com/keitaroinc/ckan-helm/blob/master/values.yaml#L7-L10).
