### ISSUE TITLE
How to change port 5000 to 80 

### ISSUE THREAD

**Issue by pribadihcr** [keitaroinc/ckan-helm#25]
Hi How to change port 5000 to 80 in values.yaml ?

**Comment by blazhovsky** [comment]
@pribadihcr if you want to change the default CKAN port from 5000 to 80 you will need to do multiple edits in the docker image that you can get [here](https://github.com/keitaroinc/docker-ckan/tree/master/images/ckan). The WSGI settings need to be changed, the generated ckan config file as well and multiple other places. You can get more info [here](https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-configuration-file)

After you do the necessary edits in the docker image you need to rebuild it and after that change the value in the helm chart.
