### ISSUE TITLE
Not able to access external DB from CKAN application

### ISSUE THREAD

**Issue by lokeshmithra** [keitaroinc/ckan-helm#32]
Hi Team,

I am trying to deploy CKAN application in Google cloud platform using helm chart version 0.1.5. But instead of creating a DB pod i am using an external DB(google cloud sql) details to save the user details. But when i tried to deploy the same i am getting error in psql-init job pod where i am able to create DB users and database with the existing psql-init.py script present in /srv/psql-init folder. But while executing  permission line to the datastore in production.ini it is providing me error.
<img width="663" alt="ckan-issue" src="https://user-images.githubusercontent.com/97042726/147964164-034e5cf1-5bd2-4852-bbcb-e1fa4eb15ea8.PNG">

Steps to re-create the issue:
1) Need to provide cloudsql details in the db section of values.yaml
2) Next deploy the pods using helm chart.

**Comment by bicisteadm** [comment]
Hello, 
my pull request #42 might bring you the details of your error.

**Comment by Filip3mac** [comment]
fixed with #42
