### ISSUE TITLE
specify repository for zookeeper image

### ISSUE THREAD

**Issue by lknite** [keitaroinc/ckan-helm#35]
With docker implementing rate limits I have selected to use a local repository.  I was able to specify this in a couple places but didn't see a way to specify the repo for zookeeper.  Ended up editing the statefulset after it was deployed to make the change.  Is it possible to do this via the helm chart?

An idea:
I've seen several charts with this up top:
```
global:
  imageRegistry: ""
```

and when used, it lets you specify your local repo, which all images get pulled from

**Comment by Filip3mac** [comment]
you can change the images in each of the dependencies so we don't need global registry for 4 images.
