### ISSUE TITLE
enabling `ckanext-saml2auth` extension

### ISSUE THREAD

**Issue by rramphal** [keitaroinc/ckan-helm#38]
Is there a recommendation on how best to enable the [ckanext-saml2auth](https://github.com/keitaroinc/ckanext-saml2auth) plugin when using this Helm chart?

**Comment by Filip3mac** [comment]
Can you give me more information on what exactly you want to do ?
Also saml2auth has documentation on how to enable the extension.

**Comment by Filip3mac** [comment]
Stale issue
