### ISSUE TITLE
error in psql-init.py due to (possibly) incorrect filename production.ini instead of ckan.ini

### ISSUE THREAD

**Issue by tristndev** [keitaroinc/ckan-helm#40]
According to [the official CKAN 2.9 documentation](https://docs.ckan.org/en/2.9/maintaining/cli.html#command-line-interface-cli), the CKAN configuration file is named `ckan.ini` from version 2.9 onwards.

The previous names (`production.ini` or `development.ini` etc.) will be phased out.

The `psql-init/psql-init.py` script still uses the `production.ini` file:
https://github.com/keitaroinc/ckan-helm/blob/44f4101c2851d91046595a47cc95b6ac3daa3127/psql-init/psql-init.py#L215-L223

 This might fail (as it did for me) depending on the Image and configuration you use.

I propose the implementation of one of following alternatives:
* at least check whether the file exists or catch the exception thrown by `subprocess.check_output(...)`
* first try the `ckan.ini` file, then the others if it fails
* make the filename settable via an environment variable

What do you think? Would be happy to implement the change..

**Comment by bicisteadm** [comment]
Hello,
I don't think the problem is in the configuration file name. The error in psql-init.py is caused by problems connecting to PostgreSQL.
My pull request #42 might bring you the details of your error.

**Comment by blazhovsky** [comment]
Hi guys, sorry for the late response. We'll look into #42 soon and test the changes.

As far as the naming for the ini file goes. This is not really a problem, you can have either ckan.ini or production/development.ini, for now all of those options work.
