### ISSUE TITLE
Installation Error when running command "helm install ckan0 keitaro-charts/ckan"

### ISSUE THREAD

**Issue by os-spb** [keitaroinc/ckan-helm#55]
Error: INSTALLATION FAILED: failed to fetch https://keitaro-charts.storage.googleapis.com/charts/ckan-v2.0.2.tgz : 404 Not Found

**Comment by Filip3mac** [comment]
Hello this was an issue with our index.yaml as it didint get the latest chart. This will be fixed soon.

**Comment by KirilPoposki98** [comment]
Issue has been fixed
