### ISSUE TITLE
ckan-helm does not work on Kubernetes 1.25

### ISSUE THREAD

**Issue by domlowe** [keitaroinc/ckan-helm#64]
This helm chart does not work on Kubernetes 1.25 (on Azure). 
Investigation shows that this is because PodDisruptionBudgets policy `v1beta1` has been removed and now only `v1` is supported.

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125

This seems to cause problems in the SOLR dependency and possibly elsewhere.
We note there is also a pull request which may partially fix this problem, however we don't think this fixes the solr dependency.

https://github.com/keitaroinc/ckan-helm/pull/62

**Comment by Filip3mac** [comment]
We are working on a dependency update, once that is done we will inform you.

**Comment by Filip3mac** [comment]
This is sorted out with https://github.com/keitaroinc/ckan-helm/tree/dependency-update but it is still a wip @domlowe

**Comment by Filip3mac** [comment]
@domlowe Fixed with https://github.com/keitaroinc/ckan-helm/tree/v3.2.0

**Comment by pribadihcr** [comment]
HI I got the following error as well:
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"

I can not find the file that contain PodDisruptionBudget.

**Comment by Filip3mac** [comment]
@pribadihcr Which version of the helm chart are you ussing?
