### ISSUE TITLE
helm install error

### ISSUE THREAD

**Issue by danseo-reisys** [keitaroinc/ckan-helm#65]
helm install ckan-p keitaro-charts/ckan
Error: INSTALLATION FAILED: YAML parse error on ckan/templates/deployment.yaml: error converting YAML to JSON: yaml: line 10: did not find expected key

any workaround?

**Comment by Filip3mac** [comment]
This issue will be fixed soon.

**Comment by danseo-reisys** [comment]
thanks.

**Comment by miguelangelch** [comment]
Hi @Filip3mac I am having the same issue working with AKS (Azure) 1.24. Is there any release date with the fix?
Thanks!

**Comment by bartek-rvk** [comment]
Hi. I was trying to install the helm release on AKS 1.23.5 and got the same issue, would be nice if you provided the fix :)

**Comment by Filip3mac** [comment]
Hey guys so we are wating on datapusher+ to make a new release where it would bit its on extension until then try using [this](https://github.com/keitaroinc/ckan-helm/tree/datapusher+) branch but you might need to edit out the datapusher+ stuff that is added.

**Comment by miguelangelch** [comment]
Hi @Filip3mac , thanks for the approach. Working with the datapusher+ I get some errors creating the container related acces to the image repository:

`t3-docker.pkg.dev/amplus-data/common/ckan-datapusher-plus:v0.10.1": failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden`

`failed to resolve reference "europe-west3-docker.pkg.dev/amplus-data/common/ckan-solar:v0.10.1": failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden `

**Comment by Filip3mac** [comment]
@miguelangelch @danseo-reisys @bartek-rvk  My bad thoose are private images can you check main branch it should be fixed now, we added a enabled feature for ckan labels.

**Comment by miguelangelch** [comment]
Hi @Filip3mac  thanks, finally I've been able to deploy it. Question... Most of the variables in the production.ini (config file) are defined to pass to the docker container in the values.yaml (plugins, title, siteurl, etc.). However, I would like to add more variables based on my plugins added.

Is there any functionality or way in the helm chart for this case?

**Comment by Filip3mac** [comment]
@miguelangelch https://github.com/keitaroinc/ckan-helm/issues/71
