### ISSUE TITLE
PSQL init job fails on OCI

### ISSUE THREAD

**Issue by hbadri3** [keitaroinc/ckan-helm#84]
I have installed ckan in OKE of OCI but getting the psql init job failing.
The logs give:

`File "/srv/app/src/ckan/ckan/cli/cli.py", line 135, in _add_ctx_object\n    ctx.obj = CtxObject(path)\n  File "/srv/app/src/ckan/ckan/cli/cli.py", line 57, in __init__\n    self.app = make_app(self.config)\n  File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 58, in make_app\n    flask_app = make_flask_stack(conf)\n  File "/srv/app/src/ckan/ckan/config/middleware/flask_app.py", line 168, in make_flask_stack\n    raise RuntimeError(u\'You must provide a value for the secret key\'\nRuntimeError: You must provide a value for the secret key with the SECRET_KEY config option\n'`

**Comment by Filip3mac** [comment]
@hbadri3 Working on a fix for this should be done soon. For now you can disable psql init and set ckan to maintenance mode/debug mode and exec into the pod and run the set-datastore command from there. The psql init only fails on the last line which sets the permissions.
@nadica-rizova Please update him once the refactor is done.

**Comment by Filip3mac** [comment]
Stale issue
