### ISSUE TITLE
helm install solr-0 pod fails 

### ISSUE THREAD

**Issue by danseo-reisys** [keitaroinc/ckan-helm#91]
helm install ckan-p keitaro-charts/ckan

solr-0 fails to start. 

kubectl logs solr-0
solr 18:29:37.39
solr 18:29:37.39 Welcome to the Bitnami solr container
solr 18:29:37.39 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-solr
solr 18:29:37.39 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-solr/issues
solr 18:29:37.39
solr 18:29:37.39 INFO  ==> ** Starting solr setup **
solr 18:29:37.40 INFO  ==> Validating settings in SOLR_* env vars...
solr 18:29:37.40 ERROR ==> Not enough nodes for the replicas and shards indicated

is there any workaround?

**Comment by Filip3mac** [comment]
Hello @danseo-reisys you need to download the values and change them, more specifically the values for the solr where you set the number of replicas and shards to a lower number.

**Comment by danseo-reisys** [comment]
reducing shards number to 1 fixed our issue.  Thanks.

**Comment by ruslanguns** [comment]
@danseo-reisys what configuration do you have for Solr? I'm still facing this issue even by lowering the replicas up to 1.

**Comment by shakesBeardZ** [comment]
the only thing that solved my problem for good is assigning values to  collectionShards and collectionReplicas in values.yaml like this: 
```
# solr.collectionShards -- Number of shards for the SOLR collection
  collectionShards: 1
  # solr.collectionReplicas -- Number of replicas for each SOLR shard
  collectionReplicas: 1
```
