### ISSUE TITLE
Solr connection refused

### ISSUE THREAD

**Issue by pribadihcr** [keitaroinc/ckan-helm#95]
Hi I got the following error:

Check_solr_connection...
HTTPConnectionPool(host='solr-headless', port=8983): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2964c964f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Unable to connect to solr...retrying.

Thanks

**Comment by pribadihcr** [comment]
solr 14:46:13.12 ERROR ==> Not enough nodes for the replicas and shards indicated

**Comment by Filip3mac** [comment]
Lower the solr replicas and shards, im guessing you are running on less nodes so that's why solr cant start up. @pribadihcr
