### ISSUE TITLE
ckan chart version 

### ISSUE THREAD

**Issue by mounajabllah** [keitaroinc/ckan-helm#97]
when i install ckan using : `helm repo add keitaro-charts https://keitaro-charts.storage.googleapis.com`  i get :   version: ckan- v3.3.0 

![image](https://github.com/keitaroinc/ckan-helm/assets/129739934/7e54bd9e-79e0-4a03-9d90-3ad4319bd865)

But if i install using the github repo tag 3.3.0 i get : Version : ckan-2.0.1  

![image](https://github.com/keitaroinc/ckan-helm/assets/129739934/268b45cb-ff7e-4999-9407-3ca244ca68f4)

**Comment by stojanovskis1** [comment]
bumped chart version https://github.com/keitaroinc/ckan-helm/pull/102
